openapi: 3.0.3
info:
  title: KMS to SDN API
  description: Messages the KMS sends to the SDN
  version: 2.0.0
servers:
  - url: https://sdn_server/api/v2/sdn
tags:
  - name: Link
  - name: Notification
paths:
  /link/registration:
    post:
      tags:
        - Link
      summary: New link registration
      description: When a source APP registers with a KMS, the KMS sends the parameters supplied by the APP to the SDN. The SDN configures a path between the source and destination, verifies the QoS and returns the key stream id and adjacent node infomation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                source:
                  type: string
                  description: IP address or UUID of the source APP
                  example: 'http://172.0.10.101:5683'
                destination:
                  type: string
                  description: IP address or UUID of the destination APP
                  example: 'http://172.0.10.102:5683'
                qos_request:
                  type: object
                  description: QoS requested by the KMS
                  example: {"key_chunk_size":4,"max_bps":128,"min_bps":64,"jitter":1,"priority":3,"timeout":50,"ttl":5,"metadata_mimetype":"application/json"}
                options:
                  type: object
                  properties:
                    multipath:
                      type: string
                      example: "enable"
                    group_key:
                      type: string   
                      description: A group key is a key for more than one destination 
                      example: [http://172.0.10.103:5683,http://172.0.10.104:5683]
              required:
                - source
                - destination
                - qos_request
      responses:
        201:
          description: Successful registration
          content:
            application/json:
              schema:
                type: object
                properties:
                  key_stream_id:
                    type: string
                    format: uuid
                  next_node_B:
                    type: array
                    description: The IP addresses of adjacent nodes
                    example: ['http://172.0.10.103:5683','http://172.0.10.104:5683']
                  qos:
                    type: object
                    description: QoS set by the SDN
                    example: {"max_bps": 0, "min_bps": 128, "jitter": 2, "priority": 0, "ttl": 1}

        400:
          description: Bad request
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/error-response'
        500:
          description: Internal error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/error-response'

    patch:
      tags:
        - Link
      summary: Destination APP registration
      description: When a destination APP registers with a KMS, the KMS informs the SDN of the destination APP'S registration. This is required in ETSI 015.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                key_stream_id:
                  type: string
                  format: uuid
                destination:
                  type: string
                  format: uuid
      responses:
        200:
          description: Successful registration
        400:
          description: Bad request
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/error-response'
        404:
          description: Not found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/error-response'
        500:
          description: Internal error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/error-response'

  /link/{key_stream_id}:
    delete:
      tags:
        - Link
      summary: Close the key stream
      parameters:
        - name: key_stream_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: Link closed
        400:
          description: Bad request
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/error-response'
        404:
          description: Not found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/error-response'
        500:
          description: Internal error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/error-response'

  /notification/registration:
    post:
      tags:
        - Notification
      summary: KMS added to network
      description: Inform the SDN of a new KMS that has been added to the network. If local instance has information about connected QKD devices or links, specify in request body.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                kms_id:
                  type: string
                device_model:
                  type: object
                  properties:
                    device_vendor:
                      type: string
                      example: 'AIT'
                      description: Vendor of the KMS
                    device_model:
                      type: string
                      example: 'AURORA KMS'
                      description: Device brand name
                    device_version:
                      type: string
                      example: '1.0.0'
                      description: version number in semantic versioning
                device_ids:
                  type: array
                  example: [UUID1, UUID2]
                link_ids:
                  type: array
                  example: [UUID1, UUID2]
              required:
                - kms_id
      responses:
        201:
          description: Registration received. Optionally additional config data provided in response. Config file data format or content not defined and expected to be vendor specific. 
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
                example: {"config":Null}
        400:
          description: Bad request
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/error-response'
        404:
          description: Not found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/error-response'
        500:
          description: Internal error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/error-response'

  /notification/status:
    patch:
      tags:
        - Notification
      summary: Status message
      description: Inform the SDN of when the KMS's status changes, e.g. the KMS goes into maintenance mode
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                state:
                  type: string
                  example: 'stopped'
                reason:
                  type: string
                  example: 'maintenance'
      responses:
        200:
          description: Status received
        400:
          description: Bad request
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/error-response'
        404:
          description: Not found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/error-response'
        500:
          description: Internal error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/error-response'

  /notification/event:
    put:
      tags:
        - Notification
      summary: Event
      description: Inform the SDN of an event
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                level:
                  type: string
                  enum: [debug, info, warning, error, critical]
                code:
                  type: integer
                  example: 14
                reason:
                  type: string
                  example: 'stopped'
      responses:
        200:
          description: Event information received
        400:
          description: Bad request
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/error-response'
        404:
          description: Not found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/error-response'
        500:
          description: Internal error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/error-response'

components:
  schemas:
    error-response:
      type: object
      properties:
        type:
          type: string
          description: 'Webpage with information on this problem'
        title:
          type: string
          description: 'Brief description of the problem'
        status:
          type: integer
          description: 'Response code or status code'
        detail:
          type: string
          description: 'Information on the problem and hints on how to solve it'
      required:
        - title
        - status
        - detail    