openapi: '3.0.3'
info:
  title: SDN to KMS API
  description: Messages the SDN sends to the KMS
  version: '2.0.0'
servers:
  - url: http://kms_sdn_server/api/v2/sdn/
tags:
  - name: Capabilities
  - name: Model 
  - name: Link
paths:
  /capabilities:
    get:
      tags:
        - Capabilities
      summary: Get the KMS's capabilities
      responses:
        200:
          description: The response states whether or not the KMS provides key relay support
          content:
            application/json:
              schema:
                type: object
                properties:
                  key_relay_support:
                    type: boolean
                    enum: [true, false]
                    example: true
                    description: true = key relay supported, false = it isn't
        400:
          description: Bad request
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/error-response'
        500:
          description: Internal error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/error-response'
  /model:
    get:
      tags:
        - Model
      summary: Get the KMS's vendor, device and version
      responses:
        200:
          description: The response contains the vendor, device and version
          content:
            application/json:
              schema:
                type: object
                properties:
                  device_model:
                    type: string
                    example: 'AIT KMS AURORA'
                    description: vendor and device
                  device_version:
                    type: string
                    example: 'v0.9.0'
                    description: version
        400:
          description: Bad request
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/error-response'
        500:
          description: Internal error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/error-response'
  /link/performance/{link_id}:
    get:
      tags:
        - Link
      summary: Get the KMS's performance data
      description: Get the performance data for the link with the given link id
      parameters:
        - name: link_id
          description: link's UUID 
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: entries
          description: Number of history records requested
          in: query
          schema:
            type: integer
      responses:
        200:
          description: The response contains KMS performance data
          content:
            application/json:
              schema:
                type: object
                properties:
                  current:
                    type: object
                    properties:
                      delta_t:
                        description: Time period over which keys are counted for the rate calculation. The unit is seconds
                        default: 10
                        type: integer
                        example: 10                        
                      IKR:
                        description: Internal Key Rate = the number of keys reserved for internal use during a delta_t period divided by delta_t
                        type: integer
                        example: 50                    
                      EXKR:
                        description: External Key Rate = the number of keys reserved for external use during a delta_t period divided by delta_t
                        type: integer
                        example: 50                    
                      SKR:
                        description: Secret Key Rate = the number of keys received from QKD devices during a delta_t period divided by delta_t
                        type: integer
                        example: 500
                      KAV:
                        description: Key Availability amount = the number of keys available to Applications during a delta_t period
                        type: integer
                        example: 400
                  history:
                    type: array
                    items:
                      type: object
                      properties:
                        timestamp:
                          type: string
                          format: date-time
                          description: ISO 8601 format
                        delta_t:
                          type: integer
                        IKR:
                          type: integer
                        SKR:
                          type: integer
                        EXKR:
                          type: integer
                        KAV:
                          type: integer
                    example:
                      - timestamp: "2024-08-27T17:41:28Z"
                        delta_t: 10
                        IKR: 144
                        SKR: 1250
                        EXKR: 320
                        KAV: 1810
                      - timestamp: "2024-08-27T17:31:28Z"
                        delta_t: 10
                        IKR: 144
                        SKR: 1250
                        EXKR: 320
                        KAV: 1024
        400:
          description: Bad request
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/error-response'
        404:
          description: Not found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/error-response'
        500:
          description: Internal error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/error-response'
  /link/relay/{key_stream_id}:
    post:
      tags:
        - Link
      summary: Create a link forwarding configuration record
      description: Create a link forwarding configuration record with the data in the request, using the given key_stream_id as an identifier
      parameters:
        - name: key_stream_id
          description: key_stream_id's UUID 
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                source:
                  type: string
                  description: Source APP's IP address or UUID 
                  example: 'http://172.0.10.101:5683'
                destination:
                  type: string
                  description: Destination APP's IP address or UUID 
                  example: 'http://172.0.10.102:5683'
                next_node_A:
                  type: array
                  description: List of adjacent nodes
                  example: ['http://172.0.10.103:5683','http://172.0.10.103:5684']  
                next_node_B:
                  type: array
                  description: List of adjacent nodes
                  example: ['http://172.0.10.104:5683','http://172.0.10.104:5684'] 
                qos_request:
                  type: object
                  description: QoS requested by the KMS
                  example: {"key_chunk_size":4,"max_bps":128,"min_bps":64,"jitter":1,"priority":3,"timeout":50,"ttl":5,"metadata_mimetype":"application/json"}
      responses:
        201:
          description: A new forwarding configuration record has been created with the given key_stream_id as an identifier, from the data in the request
        400:
          description: Bad request
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/error-response'
        500:
          description: Internal error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/error-response'
    put:
      tags:
        - Link
      summary: Update a link forwarding configuration record
      description: Replace a link forwarding configuration record with the data in the request, using the given key_stream_id as an identifier
      parameters:
        - name: key_stream_id
          description: key_stream_id's UUID 
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                source:
                  type: string
                  description: Source APP's IP address or UUID 
                  example: 'http://172.0.10.101:5683'
                destination:
                  type: string
                  description: Destination APP's IP address or UUID 
                  example: 'http://172.0.10.102:5683'
                next_node_A:
                  type: array
                  description: List of adjacent nodes
                  example: ['http://172.0.10.103:5683','http://172.0.10.103:5684']  
                next_node_B:
                  type: array
                  description: List of adjacent nodes
                  example: ['http://172.0.10.104:5683','http://172.0.10.104:5684'] 
                qos_request:
                  type: object
                  description: QoS requested by the KMS
                  example: {"key_chunk_size":4,"max_bps":128,"min_bps":64,"jitter":1,"priority":3,"timeout":50,"ttl":5,"metadata_mimetype":"application/json"}
      responses:
        200:
          description: The forwarding configuration record associated with the given key_stream_id has been replaced by the data in the request
        400:
          description: Bad request
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/error-response'
        404:
          description: Not found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/error-response'
        500:
          description: Internal error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/error-response'
    delete:
      tags:
        - Link
      summary: Delete a forwarding configuration record
      description: Delete the forwarding configuration record associated with the given key_stream_id
      parameters:
        - name: key_stream_id
          description: key stream's UUID
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: Forward table row deleted
        400:
          description: Bad request
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/error-response'
        404:
          description: Not found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/error-response'
        500:
          description: Internal error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/error-response'
  /link/{key_stream_id}:
    delete:
      tags:
        - Link
      summary: Close the link
      description: Close the link associated with the given key_stream_id
      parameters:
        - name: key_stream_id
          description: key stream's UUID
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: Link closed
        400:
          description: Bad request
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/error-response'
        404:
          description: Not found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/error-response'
        500:
          description: Internal error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/error-response'
components:
  schemas:
    error-response:
      type: object
      properties:
        type:
          type: string
          description: 'Webpage with information on this problem'
        title:
          type: string
          description: 'Brief description of the problem'
        status:
          type: integer
          description: 'Response code or status code'
        detail:
          type: string
          description: 'Information on the problem and hints on how to solve it'
      required:
        - title
        - status
        - detail